### ISSUE TITLE
Separate into two days?

### ISSUE THREAD

**Issue by deniederhut** [dlab-berkeley/programming-fundamentals#4]
@marwahaha @davclark 

Given the additional materials pulled from cornerstone, and other things we could pull in from resources like [learn enough to be dangerous](http://www.learnenough.com/command-line-tutorial) (see #3 ), does it make sense to split this into two days?

**Comment by marwahaha** [comment]
I feel like we should only have two hours of lecture/workshop material --- it doesn't make sense to me to have learners attend multiple days of "programming fundamentals".

**Comment by deniederhut** [comment]
This grew out of a conversation @pattyf and I had last semester about investing some time into making the "intro to unix" a set of workshops, with fundamentals of programming, git, and whatever we could pull from cornerstone. 

Instead of programming fundamentals days 1 and 2, maybe it makes sense to have fundamentals programming and cloud computing fundies? Especially since a lot of those other materials are about ssh, scp, terminal editors, etc? I recall some people asking about "absolute beginner" help at the last cloud compute working group.

@jackspaceBerkeley @aculich thoughts?

**Comment by davclark** [comment]
Sorry to chime in so late... I'm finally getting on top of my GitHub inbox.

I think the consensus emerging here is the right one: 
- a single 2-hour bare-fundamentals (enough to be less dangerous following instructions on the web, or in workshops)
- Working in networked environments. I'd propose the title includes "cloud" but doesn't imply that's all it's good for. Maybe "Working with networked and cloud resources"?
