### ISSUE TITLE
Challenge 2 in 1-3_test.sh fails in Windows OS

### ISSUE THREAD

**Issue by deniederhut** [dlab-berkeley/programming-fundamentals#5]
One of the challenges in pipes and redirects involves counting the number of words in all the files with `asia` in the filename.

On *NIX systems

```
cat data/articles/asia*.txt | wc -w
```

returns 77,301 words. In git-bash on windows, this returns 77,251 words.

**Comment by henchc** [comment]
this should be fixed now, i replaced the absolute 77301 with the command to yield the number
